package HBMs;
// Generated 28/05/2017 09:57:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Actividad generated by hbm2java
 */
public class Actividad  implements java.io.Serializable {


     private int id;
     private Bitacora bitacora;
     private String nombre;
     private int precio;
     private int dias;
     private int periodo;
     private Set cobros = new HashSet(0);

    public Actividad() {
    }

	
    public Actividad(int id, Bitacora bitacora, String nombre, int precio, int dias, int periodo) {
        this.id = id;
        this.bitacora = bitacora;
        this.nombre = nombre;
        this.precio = precio;
        this.dias = dias;
        this.periodo = periodo;
    }
    public Actividad(int id, Bitacora bitacora, String nombre, int precio, int dias, int periodo, Set cobros) {
       this.id = id;
       this.bitacora = bitacora;
       this.nombre = nombre;
       this.precio = precio;
       this.dias = dias;
       this.periodo = periodo;
       this.cobros = cobros;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Bitacora getBitacora() {
        return this.bitacora;
    }
    
    public void setBitacora(Bitacora bitacora) {
        this.bitacora = bitacora;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }
    public int getDias() {
        return this.dias;
    }
    
    public void setDias(int dias) {
        this.dias = dias;
    }
    public int getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(int periodo) {
        this.periodo = periodo;
    }
    public Set getCobros() {
        return this.cobros;
    }
    
    public void setCobros(Set cobros) {
        this.cobros = cobros;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Actividad other = (Actividad) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }

}


