package HBMs;
// Generated 28/05/2017 09:57:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Articulo generated by hbm2java
 */
public class Articulo  implements java.io.Serializable {


     private int id;
     private Bitacora bitacora;
     private String nombre;
     private int precio;
     private Set cobroArticulos = new HashSet(0);

    public Articulo() {
    }

	
    public Articulo(int id, Bitacora bitacora, String nombre, int precio) {
        this.id = id;
        this.bitacora = bitacora;
        this.nombre = nombre;
        this.precio = precio;
    }
    public Articulo(int id, Bitacora bitacora, String nombre, int precio, Set cobroArticulos) {
       this.id = id;
       this.bitacora = bitacora;
       this.nombre = nombre;
       this.precio = precio;
       this.cobroArticulos = cobroArticulos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Bitacora getBitacora() {
        return this.bitacora;
    }
    
    public void setBitacora(Bitacora bitacora) {
        this.bitacora = bitacora;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }
    public Set getCobroArticulos() {
        return this.cobroArticulos;
    }
    
    public void setCobroArticulos(Set cobroArticulos) {
        this.cobroArticulos = cobroArticulos;
    }


    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Articulo other = (Articulo) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }

}


