package HBMs;
// Generated 21/02/2017 08:16:46 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bitacora generated by hbm2java
 */
public class Bitacora  implements java.io.Serializable {


     private int id;
     private Usuario usuario;
     private Date fecha;
     private String estado;
     private Set articulos = new HashSet(0);
     private Set marcas = new HashSet(0);
     private Set actividads = new HashSet(0);
     private Set clientes = new HashSet(0);
     private Set movimientos = new HashSet(0);
     private Set conceptos = new HashSet(0);
     private Set cobros = new HashSet(0);

    public Bitacora() {
    }

	
    public Bitacora(int id, Usuario usuario, Date fecha, String estado) {
        this.id = id;
        this.usuario = usuario;
        this.fecha = fecha;
        this.estado = estado;
    }
    public Bitacora(int id, Usuario usuario, Date fecha, String estado, Set articulos, Set marcas, Set actividads, Set clientes, Set movimientos, Set conceptos, Set cobros) {
       this.id = id;
       this.usuario = usuario;
       this.fecha = fecha;
       this.estado = estado;
       this.articulos = articulos;
       this.marcas = marcas;
       this.actividads = actividads;
       this.clientes = clientes;
       this.movimientos = movimientos;
       this.conceptos = conceptos;
       this.cobros = cobros;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Set articulos) {
        this.articulos = articulos;
    }
    public Set getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Set marcas) {
        this.marcas = marcas;
    }
    public Set getActividads() {
        return this.actividads;
    }
    
    public void setActividads(Set actividads) {
        this.actividads = actividads;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set movimientos) {
        this.movimientos = movimientos;
    }
    public Set getConceptos() {
        return this.conceptos;
    }
    
    public void setConceptos(Set conceptos) {
        this.conceptos = conceptos;
    }
    public Set getCobros() {
        return this.cobros;
    }
    
    public void setCobros(Set cobros) {
        this.cobros = cobros;
    }




}


