package HBMs;
// Generated 21/02/2017 08:16:46 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int id;
     private Bitacora bitacora;
     private String nombre;
     private String cedula;
     private Date fnac;
     private String imagen;
     private String correo;
     private String celular;
     private String mutualista;
     private String sexo;
     private Set cobros = new HashSet(0);
     private Set marcas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int id, Bitacora bitacora, String nombre, String cedula, Date fnac, String imagen, String mutualista, String sexo) {
        this.id = id;
        this.bitacora = bitacora;
        this.nombre = nombre;
        this.cedula = cedula;
        this.fnac = fnac;
        this.imagen = imagen;
        this.mutualista = mutualista;
        this.sexo = sexo;
    }
    public Cliente(int id, Bitacora bitacora, String nombre, String cedula, Date fnac, String imagen, String correo, String celular, String mutualista, String sexo, Set cobros, Set marcas) {
       this.id = id;
       this.bitacora = bitacora;
       this.nombre = nombre;
       this.cedula = cedula;
       this.fnac = fnac;
       this.imagen = imagen;
       this.correo = correo;
       this.celular = celular;
       this.mutualista = mutualista;
       this.sexo = sexo;
       this.cobros = cobros;
       this.marcas = marcas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Bitacora getBitacora() {
        return this.bitacora;
    }
    
    public void setBitacora(Bitacora bitacora) {
        this.bitacora = bitacora;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public Date getFnac() {
        return this.fnac;
    }
    
    public void setFnac(Date fnac) {
        this.fnac = fnac;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getMutualista() {
        return this.mutualista;
    }
    
    public void setMutualista(String mutualista) {
        this.mutualista = mutualista;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Set getCobros() {
        return this.cobros;
    }
    
    public void setCobros(Set cobros) {
        this.cobros = cobros;
    }
    public Set getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Set marcas) {
        this.marcas = marcas;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Cliente other = (Cliente) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }


}


