package HBMs;
// Generated 28/05/2017 09:57:26 AM by Hibernate Tools 4.3.1



/**
 * CobroArticulo generated by hbm2java
 */
public class CobroArticulo  implements java.io.Serializable {


     private int id;
     private Articulo articulo;
     private Cobro cobro;
     private Integer cantidad;

    public CobroArticulo() {
    }

	
    public CobroArticulo(int id, Cobro cobro) {
        this.id = id;
        this.cobro = cobro;
    }
    public CobroArticulo(int id, Articulo articulo, Cobro cobro, Integer cantidad) {
       this.id = id;
       this.articulo = articulo;
       this.cobro = cobro;
       this.cantidad = cantidad;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Cobro getCobro() {
        return this.cobro;
    }
    
    public void setCobro(Cobro cobro) {
        this.cobro = cobro;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


