package HBMs;
// Generated 21/02/2017 08:16:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Concepto generated by hbm2java
 */
public class Concepto  implements java.io.Serializable {


     private int id;
     private Bitacora bitacora;
     private String nombre;
     private String descripcion;
     private Set movimientos = new HashSet(0);

    public Concepto() {
    }

	
    public Concepto(int id, Bitacora bitacora, String nombre) {
        this.id = id;
        this.bitacora = bitacora;
        this.nombre = nombre;
    }
    public Concepto(int id, Bitacora bitacora, String nombre, String descripcion, Set movimientos) {
       this.id = id;
       this.bitacora = bitacora;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.movimientos = movimientos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Bitacora getBitacora() {
        return this.bitacora;
    }
    
    public void setBitacora(Bitacora bitacora) {
        this.bitacora = bitacora;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set movimientos) {
        this.movimientos = movimientos;
    }

 @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Concepto other = (Concepto) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }


}


