package HBMs;
// Generated 21/02/2017 08:16:46 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private int id;
     private Bitacora bitacora;
     private Cliente cliente;
     private Date fecha;

    public Marca() {
    }

    public Marca(int id, Bitacora bitacora, Cliente cliente, Date fecha) {
       this.id = id;
       this.bitacora = bitacora;
       this.cliente = cliente;
       this.fecha = fecha;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Bitacora getBitacora() {
        return this.bitacora;
    }
    
    public void setBitacora(Bitacora bitacora) {
        this.bitacora = bitacora;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


