package HBMs;
// Generated 21/02/2017 08:16:46 PM by Hibernate Tools 4.3.1



/**
 * Movimiento generated by hbm2java
 */
public class Movimiento  implements java.io.Serializable {


     private int id;
     private Bitacora bitacora;
     private Concepto concepto;
     private String tipo;
     private String descripcion;
     private int importe;

    public Movimiento() {
    }

	
    public Movimiento(int id, Bitacora bitacora, Concepto concepto, String tipo, int importe) {
        this.id = id;
        this.bitacora = bitacora;
        this.concepto = concepto;
        this.tipo = tipo;
        this.importe = importe;
    }
    public Movimiento(int id, Bitacora bitacora, Concepto concepto, String tipo, String descripcion, int importe) {
       this.id = id;
       this.bitacora = bitacora;
       this.concepto = concepto;
       this.tipo = tipo;
       this.descripcion = descripcion;
       this.importe = importe;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Bitacora getBitacora() {
        return this.bitacora;
    }
    
    public void setBitacora(Bitacora bitacora) {
        this.bitacora = bitacora;
    }
    public Concepto getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(Concepto concepto) {
        this.concepto = concepto;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getImporte() {
        return this.importe;
    }
    
    public void setImporte(int importe) {
        this.importe = importe;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Movimiento other = (Movimiento) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }


}


