package HBMs;
// Generated 21/02/2017 08:16:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private Gimnasio gimnasio;
     private String username;
     private String password;
     private String nombre;
     private String imagen;
     private String hashkey;
     private Set bitacoras = new HashSet(0);
     private Set permisoUsuarios = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int id, Gimnasio gimnasio, String username, String password, String nombre, String imagen, String hashkey) {
        this.id = id;
        this.gimnasio = gimnasio;
        this.username = username;
        this.password = password;
        this.nombre = nombre;
        this.imagen = imagen;
        this.hashkey = hashkey;
    }
    public Usuario(int id, Gimnasio gimnasio, String username, String password, String nombre, String imagen, String hashkey, Set bitacoras, Set permisoUsuarios) {
       this.id = id;
       this.gimnasio = gimnasio;
       this.username = username;
       this.password = password;
       this.nombre = nombre;
       this.imagen = imagen;
       this.hashkey = hashkey;
       this.bitacoras = bitacoras;
       this.permisoUsuarios = permisoUsuarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Gimnasio getGimnasio() {
        return this.gimnasio;
    }
    
    public void setGimnasio(Gimnasio gimnasio) {
        this.gimnasio = gimnasio;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public String getHashkey() {
        return this.hashkey;
    }
    
    public void setHashkey(String hashkey) {
        this.hashkey = hashkey;
    }
    public Set getBitacoras() {
        return this.bitacoras;
    }
    
    public void setBitacoras(Set bitacoras) {
        this.bitacoras = bitacoras;
    }
    public Set getPermisoUsuarios() {
        return this.permisoUsuarios;
    }
    
    public void setPermisoUsuarios(Set permisoUsuarios) {
        this.permisoUsuarios = permisoUsuarios;
    }




}


